export const ALERTS = [
  {
    id: 'A001',
    type: 'new_property',
    title: 'New Property Match',
    message: 'A new 3BHK in Banjara Hills matches Arjun Reddy\'s preferences.',
    client: 'Arjun Reddy',
    property: 'P001',
    time: '2024-04-14T10:30:00',
    read: false,
    priority: 'high',
  },
  {
    id: 'A002',
    type: 'price_drop',
    title: 'Price Drop Alert',
    message: 'Studio Flat in Gachibowli dropped from ₹25L to ₹22L.',
    client: null,
    property: 'P003',
    time: '2024-04-13T15:00:00',
    read: false,
    priority: 'medium',
  },
  {
    id: 'A003',
    type: 'enquiry',
    title: 'New Enquiry',
    message: 'Meera Nair submitted an enquiry for the Penthouse in Madhapur.',
    client: 'Meera Nair',
    property: 'P004',
    time: '2024-04-13T09:15:00',
    read: true,
    priority: 'high',
  },
  {
    id: 'A004',
    type: 'follow_up',
    title: 'Follow-Up Reminder',
    message: 'Follow up with Rohan Gupta about Studio Flat inquiry.',
    client: 'Rohan Gupta',
    property: 'P003',
    time: '2024-04-12T14:00:00',
    read: true,
    priority: 'low',
  },
  {
    id: 'A005',
    type: 'new_property',
    title: 'New Listing Added',
    message: 'Commercial Space in HITEC City has been listed by Priya Sharma.',
    client: null,
    property: 'P006',
    time: '2024-04-11T11:00:00',
    read: true,
    priority: 'low',
  },
]
