export const CLIENTS = [
  {
    id: 'C001',
    name: 'Arjun Reddy',
    email: 'arjun.reddy@email.com',
    phone: '+91 98765 43210',
    type: 'Buyer',
    status: 'active',
    assignedAgent: 'Ravi Kumar',
    joinedDate: '2024-01-12',
    avatar: null,
    budget: { min: 5000000, max: 10000000 },
    preferences: {
      propertyType: ['Apartment', 'Villa'],
      locations: ['Banjara Hills', 'Jubilee Hills'],
      bedrooms: 3,
      amenities: ['Gym', 'Swimming Pool', 'Gated Community'],
    },
    savedProperties: ['P001', 'P004'],
    enquiries: 3,
  },
  {
    id: 'C002',
    name: 'Meera Nair',
    email: 'meera.nair@email.com',
    phone: '+91 87654 32109',
    type: 'Investor',
    status: 'active',
    assignedAgent: 'Priya Sharma',
    joinedDate: '2024-02-05',
    avatar: null,
    budget: { min: 20000000, max: 50000000 },
    preferences: {
      propertyType: ['Villa', 'Penthouse', 'Commercial'],
      locations: ['Madhapur', 'Gachibowli', 'HITEC City'],
      bedrooms: 4,
      amenities: ['Premium', 'View'],
    },
    savedProperties: ['P002', 'P004'],
    enquiries: 5,
  },
  {
    id: 'C003',
    name: 'Rohan Gupta',
    email: 'rohan.gupta@email.com',
    phone: '+91 76543 21098',
    type: 'Buyer',
    status: 'inactive',
    assignedAgent: 'Amit Verma',
    joinedDate: '2023-11-20',
    avatar: null,
    budget: { min: 2000000, max: 4000000 },
    preferences: {
      propertyType: ['Studio', 'Apartment'],
      locations: ['Gachibowli', 'Kondapur'],
      bedrooms: 1,
      amenities: ['Parking', 'Security'],
    },
    savedProperties: ['P003'],
    enquiries: 1,
  },
  {
    id: 'C004',
    name: 'Sunita Patel',
    email: 'sunita.patel@email.com',
    phone: '+91 65432 10987',
    type: 'Seller',
    status: 'active',
    assignedAgent: 'Sana Khan',
    joinedDate: '2024-03-01',
    avatar: null,
    budget: { min: 0, max: 0 },
    preferences: {
      propertyType: [],
      locations: [],
      bedrooms: 0,
      amenities: [],
    },
    savedProperties: [],
    enquiries: 0,
  },
]

export const CLIENT_TYPES = ['Buyer', 'Seller', 'Investor', 'Tenant']
